# Generated by Django 4.1.4 on 2022-12-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliatePrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=200)),
                ('bio', models.CharField(max_length=255)),
                ('earnings', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('type', models.CharField(max_length=255)),
            ],
        ),
    ]
