# Generated by Django 4.1.4 on 2022-12-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_affiliateprograms_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateprograms',
            name='cookie_expiry',
            field=models.SmallIntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='affiliateprograms',
            name='payout_threshold',
            field=models.SmallIntegerField(default='1'),
            preserve_default=False,
        ),
    ]
